import type { Request, Response } from "express";
import { Patient } from "../models/Patient.js";
import { QueueEntry } from "../models/QueueEntry.js";
import { AmbulanceReport } from "../models/AmbulanceReport.js";
import { HospitalMetrics } from "../models/HospitalMetrics.js";
import { OperationalAlert } from "../models/OperationalAlert.js";
import { Settings } from "../models/Settings.js";
import { ok } from "../utils/http.js";
export async function overview(_req: Request, res: Response) { const [activePatients, queue, ambulances, alerts, settings, recentMetrics] = await Promise.all([Patient.countDocuments({ status: { $nin: ["discharged"] } }), QueueEntry.find({ status: "active" }).sort({ position: 1 }).populate("patient"), AmbulanceReport.find({ status: "incoming" }).sort({ etaMinutes: 1 }).limit(5), OperationalAlert.find({ active: true }).sort({ severity: 1, createdAt: -1 }).limit(8), Settings.findOne({ singletonKey: "default" }), HospitalMetrics.find().sort({ measuredAt: -1 }).limit(24)]); const used = await Patient.countDocuments({ status: { $in: ["roomed", "in_treatment", "observation", "admitted"] } }); const capacity = settings?.capacity?.totalBeds ?? 48; return ok(res, { activePatients, queueLength: queue.length, incomingAmbulances: ambulances.length, bedAvailability: Math.max(0, capacity - used), capacityUtilization: Math.round((used / capacity) * 100), averageWaitMinutes: queue.length ? Math.round(queue.reduce((a, e) => a + e.estimatedWaitMinutes, 0) / queue.length) : 0, priorityDistribution: await Patient.aggregate([{ $group: { _id: "$triageStatus", count: { $sum: 1 } } }]), alerts, queue: queue.slice(0, 8), ambulances, recentMetrics }); }
export async function queueAnalytics(_req: Request, res: Response) { return ok(res, { entries: await QueueEntry.find().sort({ updatedAt: -1 }).limit(100).populate("patient"), movementPatterns: await QueueEntry.aggregate([{ $unwind: "$history" }, { $group: { _id: "$history.reason", count: { $sum: 1 } } }, { $sort: { count: -1 } }]) }); }
export async function capacity(_req: Request, res: Response) { return ok(res, await HospitalMetrics.find().sort({ measuredAt: -1 }).limit(48)); }
export async function arrivals(_req: Request, res: Response) { const since = new Date(Date.now() - 7 * 86400000); return ok(res, { patients: await Patient.aggregate([{ $match: { createdAt: { $gte: since } } }, { $group: { _id: { $dateToString: { format: "%Y-%m-%d", date: "$createdAt" } }, count: { $sum: 1 } } }, { $sort: { _id: 1 } }]), ambulances: await AmbulanceReport.aggregate([{ $match: { createdAt: { $gte: since } } }, { $group: { _id: { $dateToString: { format: "%Y-%m-%d", date: "$createdAt" } }, count: { $sum: 1 } } }, { $sort: { _id: 1 } }]) }); }
