import type { Request, Response } from "express";
import { QueueEntry } from "../models/QueueEntry.js";
import { audit } from "../services/auditService.js";
import { recalculateQueue } from "../services/queueService.js";
import { HttpError, ok } from "../utils/http.js";
export async function getQueue(_req: Request, res: Response) { const queue = await recalculateQueue(); return ok(res, queue); }
export async function reorderQueue(req: Request, res: Response) { const queue = await recalculateQueue(req.user?.id, "Manual queue recalculation requested"); await audit(req, "queue_reordered", "queue", undefined, { count: queue.length }); return ok(res, queue); }
export async function updatePriority(req: Request, res: Response) { const entry = await QueueEntry.findById(req.params.id); if (!entry) throw new HttpError(404, "Queue entry not found"); entry.priorityScore = req.body.priorityScore; entry.movementReason = req.body.reason ?? "Priority updated"; entry.history.push({ position: entry.position, priorityScore: entry.priorityScore, reason: entry.movementReason, createdBy: req.user?.id as any }); await entry.save(); const queue = await recalculateQueue(req.user?.id, "Priority score changed"); await audit(req, "queue_priority_updated", "queue", String(entry._id)); return ok(res, queue); }
export async function moveEntry(req: Request, res: Response) { const entry = await QueueEntry.findById(req.params.id); if (!entry) throw new HttpError(404, "Queue entry not found"); entry.position = req.body.position; entry.manualOverride = true; entry.overrideReason = req.body.reason ?? "Manual move"; await entry.save(); await audit(req, "queue_entry_moved", "queue", String(entry._id), { position: entry.position }); return ok(res, await QueueEntry.find({ status: "active" }).sort({ position: 1 }).populate("patient")); }
export async function manualOverride(req: Request, res: Response) { const entry = await QueueEntry.findById(req.body.queueEntryId); if (!entry) throw new HttpError(404, "Queue entry not found"); entry.manualOverride = true; entry.priorityScore = req.body.priorityScore; entry.overrideReason = req.body.reason; if (req.body.position) entry.position = req.body.position; entry.history.push({ position: entry.position, priorityScore: entry.priorityScore, reason: req.body.reason, createdBy: req.user?.id as any }); await entry.save(); await audit(req, "manual_override_performed", "queue", String(entry._id), { reason: req.body.reason }); return ok(res, await QueueEntry.find({ status: "active" }).sort({ position: 1 }).populate("patient")); }
