import { Router } from "express";
import { z } from "zod";
import { asyncHandler } from "../utils/asyncHandler.js";
import { validate } from "../middleware/validate.js";
import { requireAuth, requirePermission } from "../middleware/auth.js";
import * as auth from "../controllers/authController.js";
import * as patients from "../controllers/patientController.js";
import * as queue from "../controllers/queueController.js";
import * as ambulance from "../controllers/ambulanceController.js";
import * as triage from "../controllers/triageController.js";
import * as analytics from "../controllers/analyticsController.js";
import * as admin from "../controllers/adminController.js";
import { ambulanceSchema, idParam, loginSchema, manualOverrideSchema, noteSchema, patientCreateSchema, patientUpdateSchema, statusSchema, triageSchema } from "../validation/schemas.js";
const r = Router();
r.post("/auth/login", validate(loginSchema), asyncHandler(auth.login));
r.post("/auth/logout", requireAuth, asyncHandler(auth.logout));
r.get("/auth/me", requireAuth, asyncHandler(auth.me));
r.post("/auth/refresh", requireAuth, asyncHandler(auth.me));
r.get("/patients", requireAuth, requirePermission("patients:read"), asyncHandler(patients.listPatients));
r.post("/patients", requireAuth, requirePermission("patients:write"), validate(patientCreateSchema), asyncHandler(patients.createPatient));
r.get("/patients/:id", requireAuth, requirePermission("patients:read"), asyncHandler(patients.getPatient));
r.put("/patients/:id", requireAuth, requirePermission("patients:write"), validate(patientUpdateSchema), asyncHandler(patients.updatePatient));
r.patch("/patients/:id/status", requireAuth, requirePermission("patients:write"), validate(statusSchema), asyncHandler(patients.updateStatus));
r.patch("/patients/:id/notes", requireAuth, requirePermission("patients:write"), validate(noteSchema), asyncHandler(patients.addNote));
r.delete("/patients/:id", requireAuth, requirePermission("*"), asyncHandler(patients.deletePatient));
r.get("/queue", requireAuth, requirePermission("queue:read"), asyncHandler(queue.getQueue));
r.post("/queue/reorder", requireAuth, requirePermission("queue:write"), asyncHandler(queue.reorderQueue));
r.patch("/queue/:id/priority", requireAuth, requirePermission("queue:write"), asyncHandler(queue.updatePriority));
r.patch("/queue/:id/move", requireAuth, requirePermission("queue:write"), asyncHandler(queue.moveEntry));
r.post("/queue/manual-override", requireAuth, requirePermission("queue:write"), validate(manualOverrideSchema), asyncHandler(queue.manualOverride));
r.get("/ambulances", requireAuth, requirePermission("ambulances:read"), asyncHandler(ambulance.listAmbulances));
r.post("/ambulances", requireAuth, requirePermission("ambulances:write"), validate(ambulanceSchema), asyncHandler(ambulance.createAmbulance));
r.get("/ambulances/:id", requireAuth, requirePermission("ambulances:read"), asyncHandler(ambulance.getAmbulance));
r.patch("/ambulances/:id", requireAuth, requirePermission("ambulances:write"), asyncHandler(ambulance.updateAmbulance));
r.post("/ambulances/:id/analyze", requireAuth, requirePermission("ambulances:write"), asyncHandler(ambulance.analyzeReport));
r.post("/triage/analyze", requireAuth, requirePermission("triage:write"), validate(triageSchema), asyncHandler(triage.analyze));
r.get("/triage/:patientId/history", requireAuth, requirePermission("patients:read"), asyncHandler(triage.history));
r.get("/analytics/overview", requireAuth, requirePermission("analytics:read"), asyncHandler(analytics.overview));
r.get("/analytics/queue", requireAuth, requirePermission("analytics:read"), asyncHandler(analytics.queueAnalytics));
r.get("/analytics/capacity", requireAuth, requirePermission("analytics:read"), asyncHandler(analytics.capacity));
r.get("/analytics/arrivals", requireAuth, requirePermission("analytics:read"), asyncHandler(analytics.arrivals));
r.get("/audit", requireAuth, requirePermission("audit:read"), asyncHandler(admin.auditList));
r.get("/audit/:id", requireAuth, requirePermission("audit:read"), validate(idParam), asyncHandler(admin.auditGet));
r.get("/settings", requireAuth, requirePermission("settings:read"), asyncHandler(admin.getSettings));
r.put("/settings", requireAuth, requirePermission("*"), asyncHandler(admin.updateSettings));
r.get("/users", requireAuth, requirePermission("*"), asyncHandler(admin.listUsers));
r.post("/users", requireAuth, requirePermission("*"), validate(z.object({ body: z.object({ name: z.string(), email: z.string().email(), password: z.string().min(12), role: z.string(), department: z.string().optional() }) })), asyncHandler(admin.createUser));
r.patch("/users/:id/role", requireAuth, requirePermission("*"), asyncHandler(admin.setRole));
r.patch("/users/:id/status", requireAuth, requirePermission("*"), asyncHandler(admin.setStatus));
export default r;
